name: backEnd

on:
  workflow_call:
    inputs:
      Subscription_Id:
        required: true
        type: string

jobs:
  deploy-backEnd:
    runs-on: [self-hosted, linux]

    env:
      az_powershell_min_version: ${{ inputs.az_powershell_min_version }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          subscription-id: ${{ inputs.Subscription_Id }}
          enable-AzPSSession: true

      - shell: pwsh
        name: Show it works
        run: |
          Write-Host 'Hello!'

      - uses: azure/arm-deploy@v1
        name: Create the Resource Group for the backEnd
        id: resourcegroupbackend
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ inputs.Subscription_Id }}
          template: ARMtemplates/resourceGroup.json
          parameters: Backend/resourceGroup.parameters.json
          failOnStdErr: false

      - uses: azure/arm-deploy@v1
        name: Deploy Networking
        id: deploynetworking
        with:
          scope: resourcegroup
          region: westeurope
          resourceGroupName: 'backEnd'
          template: Bicep/network.bicep
          parameters: Backend/network.param.json
          failOnStdErr: false